name: Deploy Node + React to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

env:
  AZURE_WEBAPP_NAME: rentbazaar-app
  NODE_VERSION: 18.x

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    # ---------- фронт ----------
    - name: Install client deps
      run: npm ci
      working-directory: client

    - name: Build client
      run: CI=false npm run build
      working-directory: client

    # ---------- бэк ----------
    - name: Install backend deps (prod only)
      run: |
        npm ci --omit=dev
      working-directory: backend


    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ---------- деплой ----------
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: backend           # деплоим backend/ (внутри уже есть client/build)